### ISSUE TITLE
Helping scammers

### ISSUE THREAD

**Issue by mausworks** [harryfrey/fakegumtree#1]
Hello @harryfrey; first, thank you for the awesome documentation and rundown of this project!

While I'm a huge advocate for free information, open source & hacking, I'm also of the opinion that there is a quiet war going on. This war is not a war of fought over territory with blood &mdash; this is a war fought for capital, with _ideas_, where the truly innovative reign supreme.

There are three sides to this war: First, there's your average "victim" (read "non-techy"), who wants absolutely no part of it, and is likely not even aware that it's going on. Then you have "the scammers" which are always looking for new, better and, more sophisticated weapons; always in an effort to scam more victims, more effectively. And then lastly, there are people like you, me and, Jim Browning; doing what little we can to disrupt these efforts, and to educate people; let's call us "the good guys".

This app, while not a "technological marvel", _does carry with it some unique ideas_, which other scammers are bound to pick up on &mdash; _and you're making it really easy for them._

You've provided them with:

- The decompiled source
- Details on how the app works
- A rundown of the technologies used

While I'm not going to go into great details of *how exactly the app works* (for obvious reasons); I am going to say this; this app (as a scamming tool), is pretty much diabolically perfect.

While I absolutely respect your freedom to post and document this particular piece of software here on GitHub, I also felt an urge to tell you that, in an effort to get to know this software, its creator, and how these scammers operate; you might, in reality, actually be helping them.

Thank you for reading,
Rasmus

**Comment by harryfrey** [comment]
Hi @mausworks, thanks a lot for your comment! I've been thinking about the same thing for a bit now; yet, I did not find a definite answer for me yet.

On the one hand, of course you are absolutely right. As another reverse engineering example, take those open source Instagram, Snapchat or WhatsApp APIs. Although they are mostly frowned upon by the actual companies behind it, new ones keep popping up rather frequently. As GitHub is very well-organized, a quick search can reveal dozens of perfect fits for any scammer's desire. Sending massive amounts of spam messages and spreading fake news is as easy as never before.

On the other hand, this kind of software, just like this repository, may show fundamental flaws in the design of applications we use every day.

In contrast to the situation some time ago, malicious software nowadays almost always relies on naïve users. Stuff like actual RCE vulnerabilities becomes less and less usable for a broad audience of victims, so scammers create very convincing fake applications and trick the users into installing them. Nothing about this is "unexpected behavior": installing an APK file from an unknown source is supposed to be possible. Given the user agreed to giving them all permissions, which he did in this case, Android apps _are able to_ retrieve a unique phone identifier or a list of contacts and send all of this to any server anywhere in the world.

Why is this still possible?

Seriously, think about it: Why doesn't Android's Google Chrome always detect that the APK file is malicious? Why are apps allowed to read all contacts and send them to a server, when the user has just clicked "Agree" on a long list of permissions before he doesn't understand anyway?

I have the opinion that potential victims will never really change their mind if you just keep telling them "keep your personal information safe!", "always check the URL before entering sensitive information!" or "don't install apps from untrusted sources!". We are on the edge of a major disruption in information and software security; large companies like Google try making Android be a bit safer with every version, but nothing ever fundamentally changed. Motivating these developers to start working on that will not be possible directly; humans need extreme situations and only these will change their state of mind in the long term.

I guess in the end, this boils down to a balance between safety and freedom. I could remove this repository from GitHub again and pretend nothing ever happened. Jim Browning could delete his channel, just because through his videos, scammers may have learned how their tricks can become even more convincing. Yet, my simple mind tells me that this is not the solution.

This repository will probably never make any software developer or manager in an established software company even raise an eyebrow. Instead, several scammers will find this repository in the future, think "hey, that's nice!" and use the presented ideas for their own purposes, whatever that might mean.

But in my ideal little world, I keep trying to think that making an impact is possible.

Thank you,
Harry

**Comment by mausworks** [comment]
> On the other hand, this kind of software, just like this repository, may show fundamental flaws in the design of applications we use every day.

:clap: I think this is a good motivation for why these types of projects should/must exist, and I fully agree with this sentiment; but I also think there is sort of an obligation attached to it, and that is because:

> Why is this still possible?

OK, bare with me: I think this boils down to two things: 1) This scam; as far as the vast majority of YouTube scam-baiting-videos are concerned, _still seem kind of rare_ (please correct me if I'm wrong, is this a common thing?). Until yesterday, I had never heard of "'unverified' APK apps from scammers", I have known of "simple" Android viruses/spyware, but nothing quite as diabolical as this; and I think that is because: 2) Innovation takes time, new ideas take time to form, planning takes time, setting up websites, buying domains, and "figuring out scams"; takes time as well, maybe we're at the dawn of "pwnage-apps" &mdash; apps that you *think* are safe, but actually totally pwn your phone (read "life") without you ever knowing it.

When new technologies become popularized (e.g. PWA, WebView, and hybrid-apps), users open themselves up to new attack vectors. Developers of new technologies are _smart_, but _nobody is perfect_. New technologies will unavoidably carry with it design flaws and/or vulnerabilities &mdash; a perfect system simply cannot exist. New app/web technologies come out every odd year or so, which means plenty of new attack vectors &mdash; they just need to be found by their attackers. But again: That takes some time, applications (even for scammers) are hard to find.

So _why is this a thing_? Who knows? But I'm sure you agree with me when I claim _this shouldn't be a thing_; and that it could _likely be fixed_. And I think that it's up to the "discoverers" to e.g. file a bug report, or even try to contribute with a solution, say:

- When installing apps (apk:s) from other sources than Google play: Display a bigger warning about "installing apps from an untrusted source", and make it a bit harder to do so. As an example, on Firefox, when visiting HTTPS sites without a valid certificate; you must "add an exception", and I think a similar solution might be a viable thing in this case as well, because it will set off "red flags" &mdash; _big red screens scare people who don't know what they are doing._

I'm not saying this is a perfect (or even good) solution, and the approach might be a bit naïve. But I do think, that in order to change something, one should at least try to contribute _directly_ in at least some small way &mdash; there is (for instance) an [Android issue tracker](https://issuetracker.google.com/issues?q=status:open), maybe you/we should open an issue there? Link to this repository, your findings, Jim's video, etc.; who knows, it might help, or at start/do something, right?

> This repository will probably never make any software developer or manager in an established software company even raise an eyebrow.

Psssh &mdash; make them! :+1: 

> Instead, several scammers will find this repository in the future, think "hey, that's nice!" and use the presented ideas for their own purposes, whatever that might mean.

I think that might be a bit pessimistic! In the grand picture, this whole ordeal will have the impact you/the contributors make it have. It'll likely *not* be the catalyst for a new range of "scammer apps", but I think there will be a "difficult" new era of scammer apps/tricks: But I think that's inevitable.

> But in my ideal little world, I keep trying to think that making an impact is possible.

Making an impact is absolutely possible, and you've made one &mdash; how big, is yet to be known! :+1:

**Comment by InDieTasten** [comment]
Any scammers sophisticated enough to tailor this app to their needs or running the required backend services that are required for the application would be able to do the work done so far quite easily and quickly.

IMO, this helps _the good guys_ more than any potential scammers.

As for downloading APK files, AFAIK you already get a warning at installation phase. There should not be anything more than this. I think users should still have the freedom to run whatever they want on their devices, even though in this age, it's really just a dent in the monopoly of Apple and Google. I wouldn't be surprised however, if in the future one of them starts to make installing apps require a signature from their stores on the file, giving them complete control over what code runs on the devices. Whoever begins with that, the other one will follow quickly.

**Comment by DeenOConnor** [comment]
In modern android versions (at least in those builds i tried myself, like lineage) you can't simply install a random app you just downloaded. Instead, you are presented with a big box that says that you shouldn't trust websites and installing apps NOT from google play is dangerous. In order to make it possible to install the apk you need to go to settings and enable installing apps from unauthorized sources, where you are going to see a similar box once again.

I personally think that there's literally nothing you can do to to prevent people, who trust literally everyone, from installing malicious apps to their phones. Instead (ideally), videos, like those Jim Browning makes, should be made obligatory for all new internet users that are dealing with banking, shopping, etc. on their devices. This may sound weird, and i obviously know that this is physically impossible, but i believe that awareness is the best practice to defeat scammers.

Also, lots of people fall in the same trap while thinking that all those victims are just stupid, but they are not, they are smart enough to tell the difference between a scammer and a legitimate company representative - that's the moment when they become extremely vulnerable. Again, awareness would help i think, although it is sometimes quite hard to explain someone why you shouldn't trust a random guy who looks and acts very convincingly.

As for the app's source code - i think that it might contribute to awareness i was talking about. "Good guys" mentioned before can analyze these pieces of software and act accordingly, whether it is a youtube video or just a friendly chat with those who you know can fall a victim. Additionally you can find exploits in scammers' systems and use them to take the scammers down, although that's illegal and i'm certainly not encouraging anyone to do that.

I think this is an interesting topic, and if anyone has something else to say, i would be happy to join a discussion.

**Comment by murtraja** [comment]
> large companies like Google try making Android be a bit safer with every version

True. Now we have dynamic permissions. So the app developer (read "scammer") has to show 15 different popups for obtaining permissions, before he is able to do any damage.

**Comment by reneroth** [comment]
Just stumbled upon the video and this repository, and to be honest, I'm kind of lost on what makes this app so ingenious. To me, it seems like a standard CC phishing approach, but incredibly over-engineered. Why the attacker would even rely on a dedicated app instead of simply using the phishing website as-is is lost on me, I don't see much gained by it for all this effort.
I would really appreciate a deeper explanation, if anyone is willing to spend their time educating me :)

**Comment by murtraja** [comment]
@reneroth , the attacker simply wants to cover more ground by making the app seem much more authentic. Consider this, let's say that you are tech-savvy, of course, you know what address bar is and what URLs are. For a phishing attack, if you happen to notice that the certificate is off, or the URL is wrong, you will know that this is spam. But it is much more difficult for you to do this analysis if there is an app which seems very authentic.

So by using this "over-engineered" app, the attacker wants to trap more people

**Comment by accessiblepixel** [comment]
I'll throw my two cents in here too... While this might make someone think "oh that's a good idea to improve my scam", I think it benefits security professionals a lot more if someone does the work on decompiling stuff like this.

Because then you can look for things to keep an eye out for when developing security solutions (I believe they are called _Indicators of Compromise_) and write apps that can detect similar actions through heuristics.

I generally err on the side of the more people that know that these things are possible, the less likely we are to be caught unaware, and while maybe a scammer or two might get smarter, we as a whole community get smarter too, because more and more of us know of these things.

I certainly appreciate that someone decompiled the binary and figured out where it came from. I'd surely rather a world where this kinda stuff didn't happen, but... I also happen to like seeing how things work and understand that curiosity.

I hope everyone's having as good a year as possible :)

Thank you,
Jessica.

**Comment by mausworks** [comment]
So it's been a long time since I opened this issue. I'm fine with this being out in the open now, in 2018 (when this was relatively new) I wanted to err on the side of caution, but a lot has happened since then.

I'm closing this issue since I think that everything that can be said about it at this point, has already been said. Thanks everybody for participating. :heart:

**Comment by reneroth** [comment]
> So it's been a long time since I opened this issue. I'm fine with this being out in the open now, in 2018 (when this was relatively new) I wanted to err on the side of caution, but a lot has happened since then.

Neither in 2018 nor today was or is it relevant *at all* what you’re fine with being out in the open.

You could’ve taken this opportunity to apologize to @harryfrey instead.

**Comment by mausworks** [comment]
@reneroth I'm sorry you feel that way, and I'm confused, what do you want me to apologize for? I'm don't mean to be snide, I'm genuinely curious.

I thanked Harry for shining a light on this and educating people, but I had also a concern that this project might actually help attackers, so I opened an issue for it. I don't think I need to apologize for that, but if there's something in my original message that you think is in bad taste—please let me know.

> Just stumbled upon the video and this repository, and to be honest, I'm kind of lost on what makes this app so ingenious. To me, it seems like a standard CC phishing approach, but incredibly over-engineered. Why the attacker would even rely on a dedicated app instead of simply using the phishing website as-is is lost on me, I don't see much gained by it for all this effort.
I would really appreciate a deeper explanation, if anyone is willing to spend their time educating me :)

Are you upset that I closed the issue without spending the time to elaborate on the details? If so, here are some of the things that I felt were especially diabolical—this is all from memory from four years ago, so it's not perfect, and I'm probably missing something:

- Users are somewhat educated on phishing sites, but they generally trust apps (it was a fairly novel attack vector in 2018)
- Said IP/domain used for hosting is not visible to the user (since it's an app), and it could easily be changed, making it harder to shut down
- The app is/was (almost) indistinguishable from the original GumTree app (especially since you can't see the host/domain/IP)
- Apps can request permissions that websites cannot (e.g. access to files, sensors, contacts, messaging, etc …)
- The app can be easily be repurposed for other marketplaces/apps

This is all I could remember now, but I'm sure that if you spend the time to study the material that Harry has provided, you can come up with more concerns. Also, keep in mind that this was four years ago, and—like people here have commented on—a lot has improved since then.
